-- AlterTable
ALTER TABLE "Suppliers" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "willCome" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "willLeave" SET DATA TYPE TIMESTAMPTZ(3);
